default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  port: 3306
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  redis:
    host: redis://<%= ENV["REDIS_HOSTNAME"] %>:6379
    options:
      namespace: <%= ENV["DATABASE_NAME"] %>
      key: "_session_id"
      compress: false

development:
  <<: *default

test:
  <<: *default
  database: foobar_test

staging:
  <<: *default

production:
  <<: *default
